Feature/3828 create nuget package fr common integration test code 9469
nhs-digital-gp-it-futures/BuyingCatalogueEmailClient pull request #6
Opened 2020-08-19 13:08 UTC by SimonLLawrence

2020-08-19 14:32 UTC, bjss-chris requested changes
I think it might be worth thinking about the project name. I've suggested `NHSD.BuyingCatalogue.EmailClient.IntegrationTesting` or something along those lines.

I think we need to improve the XML docs too (making them more descriptive and adding full stops).

There are a couple of other questions/suggestions too.

2020-08-19 14:32 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServerDriver.cs
> +            }
If we don't check the value of `ScenarioContextKeys.EmailSent` why do we retrieve it? I'm guessing because we only add that context item if we send an e-mail? If that is what we do it's a tad confusing when seen from this context. When would `ScenarioContextKeys.EmailSent` be set?

Also, given that the method is `ClearAllEmailsAsync`, do we even need that check? Why not just call the delete endpoint without the guard?

2020-08-19 14:32 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServiceDriverSettings.cs
> +    ///
Missing summary.

2020-08-19 14:32 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServiceDriverSettings.cs
> +        public string SmtpServerApiBaseUrl { get; set; }
Is it worth making this read-only as it's set in the constructor?

2020-08-19 14:32 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common.csproj
> +  </ItemGroup>
Is this required?

2020-08-19 14:32 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Support/ScenarioContextKeys.cs
> +        internal const string EmailSent = nameof(EmailSent);
Just a question as per previous comment as to when this will actually be set on the scenario context?

2020-08-19 14:32 UTC, bjss-chris commented on NHSD.BuyingCatalogue.EmailClient.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common", "src\NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common\NHSD.BuyingCatalogue.Emai
I think this might be better being named something like `NHSD.BuyingCatalogue.EmailClient.IntegrationTesting`.

2020-08-20 06:17 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServerDriver.cs
> +            }
This package was original going to contains some common test steps.  Sam thought we should take them out in the end.  If we want to use the steps as they are we would need the above,   I have removed the above protection as it can be implemented if needed when the steps are put back in.

2020-08-20 06:17 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Support/ScenarioContextKeys.cs
> +        internal const string EmailSent = nameof(EmailSent);
Removed

2020-08-20 07:58 UTC, bjss-chris requested changes

2020-08-20 07:58 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.csproj
> +    <NoWarn>NU5123</NoWarn>
Do we still need this now that you've shortened the project name?

It would be better to address the warning if the we can rather than suppress it.

2020-08-20 07:58 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServerDriver.cs
> +        private readonly ScenarioContext _context;
Do we need this now?

2020-08-20 07:58 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServerDriver.cs
> +            _context = context ?? throw new ArgumentNullException(nameof(context));
As above – do we still need the `ScenarioContext` now?

2020-08-20 07:58 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServerDriver.cs
> +            return emailList.Count();
We can just use `.Count` now that we're returning a list.

2020-08-20 07:58 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServerDriver.cs
> +                    .DeleteAsync();
I think this block has one too many indents.

2020-08-20 07:58 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/Drivers/EmailServiceDriverSettings.cs
> +using System.Text;
Do we need all these?

2020-08-20 08:16 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTests.Common/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.csproj
> +    <NoWarn>NU5123</NoWarn>
Just ran a test , one of the folders has the old name an is causing an issue, i will fix it.

2020-08-20 08:22 UTC, bjss-chris approved these changes
👍

2020-08-20 09:34 UTC, sam-roberts-bjss requested changes
Added a few comments as @bjss-chris has not had much exposure to the Ordering API & I am going to be using this library very shortly. Just a few minor comments. Will need to look at some of the summary comments, to tidy them up (maybe one for discussion at the coding standards meeting to agree a format), but this can be tackled as part of another task.

Once we start using it hopefully this will give us a better idea for improvements. I know at the moment we just clear all emails but if we wanted to run the tests in parallel this would be a problem. Really we want to way to delete only the emails the test knows about. Again this can obviously be part of another task.

2020-08-20 09:34 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServiceDriverSettings.cs
> +            SmtpServerApiBaseUrl = smtpServerApiBaseUrl;
Should this allow an empty string or null?

2020-08-20 09:34 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.csproj
> +    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.3.57" />
It looks like we are missing the FxCop analyzers i.e. look to add the following package reference.

```
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

2020-08-20 09:34 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +        /// <returns>A IReadOnlyList of<see cref="Email"/></returns>
Good use of the <see /> tag... just need to be careful of spacing.

For example:
`of<see cref="Email"/>`
-> 
`of <see cref="Email"/>`

2020-08-20 10:03 UTC, sam-roberts-bjss approved these changes
👍

2020-08-20 10:05 UTC, bjss-chris requested changes

2020-08-20 10:05 UTC, bjss-chris commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServiceDriverSettings.cs
>          public EmailServiceDriverSettings(string smtpServerApiBaseUrl)
This is triggering an FxCop warning causing the build to fail.

Can we either update the property and the constructor parameter to be `Uri` or alternatively add an additional constructor that takes a `Uri` and this constructor just invokes the `Uri` constructor?

2020-08-20 10:09 UTC, bjss-chris approved these changes

2020-08-20 10:09 UTC, sam-roberts-bjss approved these changes

2020-08-20 10:10 UTC, merged