3929: Added support for reading the Attachments
nhs-digital-gp-it-futures/BuyingCatalogueEmailClient pull request #7
Opened 2020-08-20 10:29 UTC by SimonLLawrence

2020-08-24 15:18 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailResponseAttachmentBuilder.cs
> +            ContentType = "application/json";
You can use MediaTypeNames.Application.Json rather than hardcoding the string "application/json"

2020-08-24 15:19 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailResponseAttachmentBuilder.cs
> +            return new EmailResponseAttachment(ContentType,FileName);
Can you seperate the parameters with a space

2020-08-24 15:19 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +            _attachmentContent = new List<EmailResponseAttachment> {EmailResponseAttachmentBuilder.Create().Build()};
Add a space either side of the { }

2020-08-24 15:21 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +        public EmailServerDriverResponseBuilder WithTo(string name,string address)
Seperate the parameters with a space

2020-08-24 15:21 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +                _to.Add(new EmailAddress(name,address));
Same here (space

2020-08-24 15:22 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +            if (attachmentMetadata == null)
is null

2020-08-24 15:22 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +            return  new EmailResponse
Double space here

2020-08-24 15:24 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Data/EmailResponseAttachment.cs
> +    public class EmailResponseAttachment
sealed

2020-08-24 15:25 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +            if (emailResponse == null)
is null

2020-08-24 15:25 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Extensions/EmailAttachmentDataExtensions.cs
> +            if (attachment == null)
is

2020-08-24 15:25 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Extensions/EmailAttachmentDataExtensions.cs
> +            if (settings==null)
is null, plus add spacing

2020-08-24 15:26 UTC, RuthBerry96 commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailAttachmentTests.cs
> +            var emailId = "Id";
const string

2020-08-24 15:26 UTC, RuthBerry96 commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailAttachmentTests.cs
> +            var contentType = new ContentType("application/json");
You can use MediaTypeNames.Application.Json rather than hardcoding the string "application/json"

2020-08-24 15:29 UTC, RuthBerry96 commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +
Extra space

2020-08-25 08:59 UTC, sam-roberts-bjss requested changes

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +            if (address == null )
Not sure about this approach the method seems to be doing two things breaking the single responsibility pattern. A user might want a test that involved a `NULL` email address but the behaviour would clear the list instead. This would seem unexpected to me as a consumer of this class.

Would it be clearer to the consumer of this code to have a method to clear the list of email address's instead? Or maybe don't initialise the class with any items as a default? How would this effect your tests?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +                Id = @"ID"+ (++IdNumber),
As mentioned above, could this just be a `GUID` instead? Is it a good idea to use a static number in code that could run in parallel without any locking code?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Data/Email.cs
> +        public List<EmailAddress> To { get;} = new List<EmailAddress>();
Spacing?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Data/EmailAddress.cs
> +        /// <summary>
New line?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Data/EmailAddress.cs
> +        public EmailAddress(string name , string address)
Spacing?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Data/EmailResponse.cs
> +        public string? Id { get; set; }
New lines between properties? Just makes the code neater & easier to read.

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Data/EmailResponseAttachment.cs
> +        public string? ContentType { get; set; }
New lines?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Data/EmailAttachmentData.cs
> +        public List<byte> AttachmentData { get; } = new List<byte>();
New lines?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +        public async Task<byte[]> DownloadAttachment(EmailAttachmentData attachment)
Please add 'Async' to the end of the method name to follow our convention.

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +            var emails=  responseBody.Select(ProcessEmailResponse).ToList();
Spacing?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +                var emailId = emailResponse.Id ?? throw new NullReferenceException();
Any reason for throwing the `NullReferenceException`'s here? The ID of the email could be moved into the Email class, then the attachment doesn't need it, unless some tests rely on it.

2020-08-25 08:59 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailAttachmentTests.cs
> +        const string fileName = "file.pdf";
private?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailAttachmentTests.cs
> +        private static readonly ContentType contentType = new ContentType(MediaTypeNames.Application.Json);
Member variables usually follow our convention with an underscore e.g. _contentType

2020-08-25 08:59 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +    internal static class EmailServerDriverTests
Are our test classes usually static? Any reason for the change?

2020-08-25 08:59 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +                resultEmail.From.Should().BeEquivalentTo(email.From);
Would it be possible to have one assert statement to check the result as a whole? Just makes the test easier to understand & less maintenance if we add another property in the future.

2020-08-25 09:40 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +            if (address == null )
Added clear methods

2020-08-25 09:55 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +                var emailId = emailResponse.Id ?? throw new NullReferenceException();
You need the ID and the Filename to download the attachment.  There is an extension method that allows you to download the attachment from the EmailAttachmentData class. So its there too ensure that EmailAttachmentData has everything it need to download the attachment data.  Due to the fact we are using nullable it needs to be checked or there is a warning message to deal with.

2020-08-25 09:58 UTC, SimonLLawrence commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailAttachmentTests.cs
> +        private static readonly ContentType contentType = new ContentType(MediaTypeNames.Application.Json);
Ruth requested this be a const , and visual studio says consts should be named with a capital letter and no unserscore. FileName ?

2020-08-25 10:08 UTC, SimonLLawrence commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +    internal static class EmailServerDriverTests
We get the following warning if the class is not static 

4>EmailServerDriverTests.cs(23,27,23,49): warning CA1812: EmailServerDriverTests is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).

2020-08-25 10:13 UTC, SimonLLawrence commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +                resultEmail.From.Should().BeEquivalentTo(email.From);
Attachments are different, and properties have different names. So you cant do a top level comparison.

2020-08-25 11:25 UTC, RuthBerry96 commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +        private readonly EmailServerDriverSettings _emailServerDriverSettings;
This file can be removed, if you now have EmailServicerDriverSettings

2020-08-25 11:34 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +        private readonly EmailServerDriverSettings _emailServerDriverSettings;
Not following what you mean here ?

2020-08-25 11:42 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +        private readonly EmailServerDriverSettings _emailServerDriverSettings;
Did you mean attribute?

2020-08-25 11:56 UTC, SimonLLawrence commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +                resultEmail.From.Should().BeEquivalentTo(email.From);
I have renamed some properties, but the attachments are different.

2020-08-25 13:00 UTC, sam-roberts-bjss requested changes

2020-08-25 13:00 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailAttachmentTests.cs
> +        private static readonly ContentType contentType = new ContentType(MediaTypeNames.Application.Json);
Yeah good shout on the const. That does follow our naming convention to yeah stick with that 👍 Though the `contentType`  variable still doesn't start with an underscore.

2020-08-25 13:00 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +    internal class EmailServerDriverTests
Sealed?

2020-08-25 13:00 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +        public static void Constructor_NullMessage_ThrowsException()
I thought if you removed static from the class name, you could remove it from each of the methods? This matches our coding style within the other projects.

2020-08-25 13:00 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +            return await attachment.DownloadDataAsync(_emailServerDriverSettings);
Could the extension method be moved into this class?

2020-08-25 13:00 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +                var emailId = emailResponse.Id ?? throw new NullReferenceException();
Might be able to fix this by using a the syntax `string?` rather than throwing a NullReferenceException.

2020-08-25 13:00 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +            var emails =  responseBody.Select(ProcessEmailResponse).ToList();
Would it be possible to download the email attachments as part of this process? I don't think we have a requirement just yet to manage this better. That way the test doesn't have to know about calling another function. One call to get all emails and their attachments.

2020-08-25 13:32 UTC, sam-roberts-bjss commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +        public static void Constructor_NullMessage_ThrowsException()
Ignore this the above comment. Even though this is different across all of our other applications @bjss-chris has raised a good point to keep consistency within the repository that there is no need for these methods to be changed to non static. This means the Test Class can be changed back to static.

2020-08-25 13:47 UTC, SimonLLawrence commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Builders/EmailServerDriverResponseBuilder.cs
> +        private static int IdNumber = 0;
Tests now use a GUID and  int based string is gone.

2020-08-25 13:49 UTC, SimonLLawrence commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +    internal class EmailServerDriverTests
changed back to static and static cannot be sealed

2020-08-25 14:34 UTC, RuthBerry96 commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServerDriverTests.cs
> +        //[SuppressMessage("ReSharper", "ObjectCreationAsStatement", Justification = "Exception testing")]
Can this comment be removed

2020-08-25 14:34 UTC, RuthBerry96 commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailAttachmentTests.cs
> +        private static readonly byte[] dataArray =  {23,34,54};
Can there be spacing between this e.g. { 23, 34, 54 }

2020-08-25 14:36 UTC, RuthBerry96 commented on tests/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting.UnitTests/EmailServiceDriverSettingsTests.cs
> +    [Parallelizable(ParallelScope.All)]
This file can be deleted

2020-08-25 14:39 UTC, sam-roberts-bjss commented on src/NHSD.BuyingCatalogue.EmailClient.IntegrationTesting/Drivers/EmailServerDriver.cs
> +        public async Task<byte[]> DownloadAttachmentAsync(string? emailId,string? fileName)
Does this need to be public?

2020-08-25 15:30 UTC, RuthBerry96 approved these changes
👍

2020-08-25 15:40 UTC, sam-roberts-bjss approved these changes

2020-08-25 15:40 UTC, merged